// Generated by https://quicktype.io

export type Items = {
  items: Item[];
}

export type Item = {
  kind:    string;
  etag:    string;
  id:      ID;
  snippet: Snippet;
}

export type ID = {
  kind:    string;
  videoId: string;
}

export type Snippet = {
  publishedAt:          string;
  channelId:            string;
  title:                string;
  description:          string;
  thumbnails:           Thumbnails;
  channelTitle:         string;
  liveBroadcastContent: string;
  publishTime:          string;
}

export interface Thumbnails {
  default: Default;
  medium:  Default;
  high:    Default;
}

export interface Default {
  url:    string;
  width:  number;
  height: number;
}
