//% libs
import Head from "next/head";
import {getWatchedItAgainVideos} from "../lib/videos";

//% comps
import Banner from "../components/banner/banner";
import NavBar from "../components/nav/navbar";
import SectionCards from "../components/card/section-cards";

//% styles
import styles from "../styles/Home.module.css";

//% data
import {getVideos} from "../lib/videos";

//% types
import type {NextPage} from "next";
import type {
  InferGetServerSidePropsType,
  GetServerSidePropsContext,
  GetServerSidePropsResult,
} from "next";
import {VideoT} from "../types/youtube-api";
import {VideoStatsT} from "../types";

type ServerPropsResultsT =
  | Omit<VideoT, "description" | "publishedAt" | "channelTitle" | "statistics">
  | unknown; //! Change

type ServerPropsT_Index = {
  [idx: string]: ServerPropsResultsT[];
};

export const getServerSideProps = async (
  context_: GetServerSidePropsContext
) => {
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getVideos("popular");
  const watchItAgainVideos = await getWatchedItAgainVideos();

  const result: GetServerSidePropsResult<ServerPropsT_Index> = {
    props: {
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
      watchItAgainVideos,
    },
  };

  return {
    props: {
      disneyVideos,
      travelVideos,
      productivityVideos,
      popularVideos,
      watchItAgainVideos,
    },
  };
};

const Home: NextPage<
  InferGetServerSidePropsType<typeof getServerSideProps>
> = props => {
  const {
    disneyVideos,
    travelVideos,
    productivityVideos,
    popularVideos,
    watchItAgainVideos,
  } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <Banner
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.webp"
        />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} />
          <SectionCards
            title="Watched it again"
            videos={watchItAgainVideos}
            size="small"
          />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </main>
    </div>
  );
};

export default Home;
